# Autogenerated with DRAKON Editor 1.31

def Nachbar betritt Etage():
    #item 6
    if ranf() < 0.5:
        #item 9
        DropDelay = ranf() * AVG_DROP_DELAY
        timer_dropTrash.start()
    else:
        #item 10
        DropTrashOnThisFloor = false
    #item 110001
    if Event == Nachbar.on_Muellhalde_entered():
        #item 21
        if ranf() < .25:
            #item 24
            dropTrash()
            #item 20
            timer_dropTrash.stop()
        else:
            pass
    else:
        #item 110002
        if Event == _on_change_floor():
            #item 19
            timer_dropTrash.stop()
        else:
            #item 110003
            if Event == _on_timer_dropTrash_timeout():
                pass
            else:
                #item 110004
                raise Exception("Not expected:  " + str(Event))
            #item 18
            dropTrash()


